version: 2.1

aliases:
  - &checkout
    checkout
  - &store_artifacts
    store_artifacts:
      path: coverage

job_node_10: &job_node_10
  docker:
    - image: circleci/node:10

job_node_11: &job_node_11
  docker:
    - image: circleci/node:11

job_node_12: &job_node_12
  docker:
    - image: circleci/node:12

run_yarn: &run_yarn
  name: Install yarn packages
  command: yarn install --frozen-lockfile

save_yarn: &save_yarn
  save_cache:
    name: Save Yarn Package Cache
    key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - node_modules

restore_yarn: &restore_yarn
  restore_cache:
    name: Restore Yarn Package Cache
    key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

commands:
  nodejs:
    description: Primary flow
    steps:
    - *checkout
    - <<: *restore_yarn
    - run:
        <<: *run_yarn
    - <<: *save_yarn
    - run:
        name: Linting
        command: yarn lint
    - run:
        name: Create build
        command: yarn build
    - run:
        name: Create JS template
        command: node ./dist/index.js --interactive=false --name=javascript_template --description=javascript_bot --author=circleci --license=MIT --repo='https://github.com/favna/jsbot' --gitinit=no --manager=yarn --template=javascript --prefix=. --ownerid=1234 --token=12345
    - run:
        name: Create TS template
        command: node ./dist/index.js --interactive=false --name=typescript_template --description=typescript_bot --author=circleci --license=MIT --repo='https://github.com/favna/tsbot' --gitinit=no --manager=yarn --template=typescript --prefix=. --ownerid=1234 --token=12345
    - run:
        name: Test outputs
        command: yarn test:ci

# List of jobs
jobs:
  node-v10:
    <<: *job_node_10
    steps:
      - nodejs
  node-v11:
    <<: *job_node_11
    steps:
      - nodejs
  node-v12:
    <<: *job_node_12
    steps:
      - nodejs

workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v10
      - node-v11
      - node-v12